# Generated by Django 4.0.5 on 2022-06-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityinsocialnetworks',
            options={'verbose_name': 'Активность в соц. сетях', 'verbose_name_plural': 'Активность в соц. сетях'},
        ),
        migrations.AlterModelOptions(
            name='activityonjnlinetradingplatforms',
            options={'verbose_name': 'Активность на торговых интернет-платформах', 'verbose_name_plural': 'Активность на торговых интернет-платформах'},
        ),
        migrations.AlterModelOptions(
            name='age',
            options={'verbose_name': 'Возраст', 'verbose_name_plural': 'Возраст'},
        ),
        migrations.AlterModelOptions(
            name='anonymityontheinternet',
            options={'verbose_name': 'Анонимности в Интернете', 'verbose_name_plural': 'Анонимности в Интернете'},
        ),
        migrations.AlterModelOptions(
            name='levelofawareness',
            options={'verbose_name': 'Уровень осведомленности', 'verbose_name_plural': 'Уровень осведомленности'},
        ),
        migrations.AlterModelOptions(
            name='messageboardactivity',
            options={'verbose_name': 'Активность доски объявлений', 'verbose_name_plural': 'Активность доски объявлений'},
        ),
        migrations.AlterModelOptions(
            name='myquesyion',
            options={'ordering': ['-created'], 'verbose_name': 'Опросник пользователя', 'verbose_name_plural': 'Опросники'},
        ),
        migrations.AlterModelOptions(
            name='useofreactionenhancers',
            options={'verbose_name': 'Применение усилителей реакции', 'verbose_name_plural': 'Применение усилителей реакции'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Социальный статус(работа)', 'verbose_name_plural': 'Социальный статус(работа)'},
        ),
        migrations.RemoveField(
            model_name='myquesyion',
            name='result',
        ),
        migrations.AlterField(
            model_name='age',
            name='user_age',
            field=models.CharField(max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='myquesyion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
