# Generated by Django 4.0.5 on 2022-06-25 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_activityinsocialnetworks_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_position', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиция',
            },
        ),
        migrations.AddField(
            model_name='myquesyion',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.position', verbose_name='Позиция'),
        ),
    ]
